Return-Path: <samba-technical-bounces@lists.samba.org>
X-Original-To: lists+samba-technical@lfdr.de
Delivered-To: lists+samba-technical@lfdr.de
Received: from hr1.samba.org (hr1.samba.org [IPv6:2a01:4f8:192:486::1:0])
	by mail.lfdr.de (Postfix) with ESMTPS id E9DC12AD166
	for <lists+samba-technical@lfdr.de>; Tue, 10 Nov 2020 09:38:47 +0100 (CET)
DKIM-Signature: v=1; a=rsa-sha256; q=dns/txt; c=relaxed/relaxed;
	d=lists.samba.org; s=2954282; h=Cc:From:List-Id:Subject:To:Date;
	bh=upTAR4UgpUEgmn+0ISIQCeyhPPafu2HirCjSSyHuvdg=; b=J28IsDNaWpxaFyTXEqVdYRGpE7
	1/7iGlQjUo+rzv4gQpoGu2SGidQrDEir9ppqm18Anxb+1hTvZHhBJdcY7QISYZ3ssYDSYXKfHKLw7
	pM/zWZ7x0Yhm7bfT9Ag20P/Sk7DJAjs4V1fYjkN4YD1JNBNcfldhMjdCHj/yA9ZPEKO1uZHR1oDc3
	DhD8oahLcrNFZgVRI5G6aMKSIzC+LX88QwPGWI1ZFIGJ1ypEivD3fjSSJ4k32UkhSByz9d11PGBkz
	vEeF2nIQnYYUhUxA+ugkuQ4SbYFl47h6FyetqYi0QdxRa4w44PEUcaLjs87AQaRldsaAGvfxNVQIu
	rTQdR8Rw==;
Received: from ip6-localhost ([::1]:21218 helo=hr1.samba.org) 
	by hr1.samba.org with esmtp (Exim)
	id 1kcP9z-000dEH-Rb; Tue, 10 Nov 2020 08:37:51 +0000
Received: from sky.osstech.co.jp ([153.120.181.221]:54028) 
 by hr1.samba.org with esmtps (TLS1.3:ECDHE_RSA_CHACHA20_POLY1305:256)
 (Exim) id 1kcP9t-000dEA-SA
 for samba-technical@lists.samba.org; Tue, 10 Nov 2020 08:37:49 +0000
Received: from localhost (localhost [127.0.0.1])
 by sky.osstech.co.jp (Postfix) with ESMTP id F2E8733B253C;
 Tue, 10 Nov 2020 17:18:37 +0900 (JST)
Received: from sky.osstech.co.jp ([127.0.0.1])
 by localhost (sky.osstech.co.jp [127.0.0.1]) (amavisd-new, port 10024)
 with ESMTP id YU_gHaYCSd-s; Tue, 10 Nov 2020 17:18:32 +0900 (JST)
Received: from ocean.lan.osstech.co.jp (ldap1.lan.osstech.co.jp
 [222.158.192.65])
 by sky.osstech.co.jp (Postfix) with ESMTPS id E5AF933B2539;
 Tue, 10 Nov 2020 17:18:32 +0900 (JST)
Received: from sugar.osstech.co.jp (sugar.vpn.osstech.co.jp [10.8.1.20])
 by ocean.lan.osstech.co.jp (Postfix) with ESMTP id 805AE4028BBE;
 Tue, 10 Nov 2020 17:18:32 +0900 (JST)
Received: from sugar.sugar.osstech.co.jp (localhost [127.0.0.1])
 by sugar.osstech.co.jp (Postfix) with ESMTP id 69BD2106F085;
 Tue, 10 Nov 2020 17:21:17 +0900 (JST)
Date: Tue, 10 Nov 2020 17:21:17 +0900
Message-ID: <87pn4loc5e.wl-fumiyas@osstech.co.jp>
To: Andrew Bartlett <abartlet@samba.org>
Subject: Re: Eaten by autobuild?
In-Reply-To: <b70db8da503720b24dbadcba32d95556c108d01a.camel@samba.org>
References: <b70db8da503720b24dbadcba32d95556c108d01a.camel@samba.org>
User-Agent: Wanderlust/2.15.9 (Almost Unreal) Emacs/27.1 Mule/6.0
Organization: OSS Technology Corp. / Samba-JP / LDAP-JP / Apache-JP
MIME-Version: 1.0 (generated by SEMI-EPG 1.14.7 - "Harue")
Content-Type: text/plain; charset=US-ASCII
Content-Transfer-Encoding: quoted-printable
X-BeenThere: samba-technical@lists.samba.org
X-Mailman-Version: 2.1.29
Precedence: list
List-Id: "Discussions on Samba internals. For general questions please
 subscribe to the list samba@lists.samba.org"
 <samba-technical.lists.samba.org>
List-Unsubscribe: <https://lists.samba.org/mailman/options/samba-technical>,
 <mailto:samba-technical-request@lists.samba.org?subject=unsubscribe>
List-Archive: <http://lists.samba.org/pipermail/samba-technical/>
List-Post: <mailto:samba-technical@lists.samba.org>
List-Help: <mailto:samba-technical-request@lists.samba.org?subject=help>
List-Subscribe: <https://lists.samba.org/mailman/listinfo/samba-technical>,
 <mailto:samba-technical-request@lists.samba.org?subject=subscribe>
From: SATOH Fumiyasu via samba-technical <samba-technical@lists.samba.org>
Reply-To: SATOH Fumiyasu <fumiyas@osstech.co.jp>
Cc: Upstream Samba Technical Mailing list <samba-technical@lists.samba.org>
Errors-To: samba-technical-bounces@lists.samba.org
Sender: "samba-technical" <samba-technical-bounces@lists.samba.org>

Hi,

How about the following patches?

=46rom b51714389dea766a49118187c5954b7ccaf92587 Mon Sep 17 00:00:00 2001
From: SATOH Fumiyasu <fumiyas@osstech.co.jp>
Date: Tue, 10 Nov 2020 17:15:42 +0900
Subject: [PATCH] autobuild: Encode text/plain into base64 to wrap long-lines

MIMEText(text, 'plain', 'utf-8') encodes the text into
base64 and adds 'Content-Transfer-Encoding: base64' header.
---
 script/autobuild.py | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/script/autobuild.py b/script/autobuild.py
index 24baa0fa9f2..a76309df8a2 100755
--- a/script/autobuild.py
+++ b/script/autobuild.py
@@ -1112,7 +1112,7 @@ def send_email(subject, text, log_tar):
     outer['From'] =3D options.email_from
     outer['Date'] =3D email.utils.formatdate(localtime=3DTrue)
     outer.preamble =3D 'Autobuild mails are now in MIME because we optiona=
lly attach the logs.\n'
-    outer.attach(MIMEText(text, 'plain'))
+    outer.attach(MIMEText(text, 'plain', 'utf-8'))
     if options.attach_logs:
         with open(log_tar, 'rb') as fp:
             msg =3D MIMEApplication(fp.read(), 'gzip', email.encoders.enco=
de_base64)
--=20
2.29.1

On Tue, 10 Nov 2020 15:51:47 +0900,
samba-technical@lists.samba.org wrote:
>=20
> When your autobuild is eaten, remember to check autobuild.log.
>=20
> I didn't get an autobuild failure mail because that comes from the
> autobuild script, which failed to fire out the mail:
>=20
> Traceback (most recent call last):
>   File "script/autobuild.py", line 1324, in <module>
>     elapsed_time, log_base=3Doptions.log_base)
>   File "script/autobuild.py", line 1197, in email_failure
>     text, logs)
>   File "script/autobuild.py", line 1130, in send_email
>     s.sendmail(options.email_from, [options.email], content)
>   File "/usr/lib/python3.6/smtplib.py", line 888, in sendmail
>     raise SMTPDataError(code, resp)
> smtplib.SMTPDataError: (550, b'maximum allowed line length is 998
> octets, got 1756')
>=20
> This is because of this lovely line, which it wanted to put into the mail=
 as context for the failure:
> test: running (/usr/bin/perl /m/abartlet/aMASTER/b2752753/samba-o3/selfte=
st/selftest.pl --target=3Dsamba --prefix=3D./bin/ab --srcdir=3D/m/abartlet/=
aMASTER/b2752753/samba-o3 --exclude=3D/m/abartlet/aMASTER/b2752753/samba-o3=
/selftest/skip --testlist=3D"/usr/bin/python3 /m/abartlet/aMASTER/b2752753/=
samba-o3/selftest/tests.py|" --testlist=3D"/usr/bin/python3 /m/abartlet/aMA=
STER/b2752753/samba-o3/source3/selftest/tests.py|" --testlist=3D"/usr/bin/p=
ython3 /m/abartlet/aMASTER/b2752753/samba-o3/source4/selftest/tests.py|"  -=
-exclude=3D/m/abartlet/aMASTER/b2752753/samba-o3/selftest/slow --nss_wrappe=
r_so_path=3D/m/abartlet/aMASTER/b2752753/samba-o3/bin/default/third_party/n=
ss_wrapper/libnss-wrapper.so --resolv_wrapper_so_path=3D/m/abartlet/aMASTER=
/b2752753/samba-o3/bin/default/third_party/resolv_wrapper/libresolv-wrapper=
.so --uid_wrapper_so_path=3D/m/abartlet/aMASTER/b2752753/samba-o3/bin/defau=
lt/third_party/uid_wrapper/libuid-wrapper.so --socket_wrapper_so_path=3D/m/=
abartlet/aMASTER/b2752753/samba-o3/bin/default/third_party/socket_wrapper/l=
ibsocket-wrapper.so --socket-wrapper --exclude=3Dselftest/slow-none --inclu=
de-env=3Dnone && touch ./bin/ab/st_done) | /usr/bin/python3 -u /m/abartlet/=
aMASTER/b2752753/samba-o3/selftest/filter-subunit --expected-failures=3D/m/=
abartlet/aMASTER/b2752753/samba-o3/selftest/knownfail --expected-failures=
=3D/m/abartlet/aMASTER/b2752753/samba-o3/selftest/knownfail.d --flapping=3D=
/m/abartlet/aMASTER/b2752753/samba-o3/selftest/flapping --flapping=3D/m/aba=
rtlet/aMASTER/b2752753/samba-o3/selftest/flapping.d --fail-immediately --ex=
pected-failures=3D/m/abartlet/aMASTER/b2752753/samba-o3/selftest/knownfail_=
heimdal_kdc | tee ./bin/ab/subunit | /usr/bin/python3 -u /m/abartlet/aMASTE=
R/b2752753/samba-o3/selftest/format-subunit --prefix=3D./bin/ab --immediate
> LD_PRELOAD=3D/m/abartlet/aMASTER/b2752753/samba-o3/bin/default/third_part=
y/nss_wrapper/libnss-wrapper.so:/m/abartlet/aMASTER/b2752753/samba-o3/bin/d=
efault/third_party/resolv_wrapper/libresolv-wrapper.so:/m/abartlet/aMASTER/=
b2752753/samba-o3/bin/default/third_party/socket_wrapper/libsocket-wrapper.=
so:/m/abartlet/aMASTER/b2752753/samba-o3/bin/default/third_party/uid_wrappe=
r/libuid-wrapper.so
>=20
> Just in the hope this helps someone else (or someone knows how to fix it).

--=20
-- Name: SATOH Fumiyasu @ OSS Technology Corp. (fumiyas @ osstech co jp)
-- Business Home: https://www.OSSTech.co.jp/
-- GitHub Home: https://GitHub.com/fumiyas/
-- PGP Fingerprint: BBE1 A1C9 525A 292E 6729  CDEC ADC2 9DCA 5E1C CBCA

